name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.neehith18 }}
          password: ${{ secrets.Sujatha@123 }}

      - name: Build and Push Docker Image
        run: |
          docker build -t YOUR_DOCKERHUB_USERNAME/wisecow:latest .
          docker push YOUR_DOCKERHUB_USERNAME/wisecow:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure Kubernetes
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
