 name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/wisecow-app:latest .
          docker push your-dockerhub-username/wisecow-app:latest

      # Step 4: Set up Kubernetes and deploy
      - name: Set up Kubernetes
        run: |
          kubectl config set-cluster your-cluster-name --server=https://your-kubernetes-api
          kubectl config set-credentials your-username --token=${{ secrets.KUBERNETES_TOKEN }}
          kubectl config set-context your-context --cluster=your-cluster-name --user=your-username
          kubectl config use-context your-context

      # Step 5: Apply Kubernetes configuration files
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml
