name: System Health Monitoring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run system health monitoring script
      run: |
        chmod +x monitor.sh
        ./monitor.sh
